#Skip tests as they require Arquillian
language: java
install: mvn clean install -Dgpg.skip=true -DskipTests
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script: /bin/true
cache:
  directories:
  - $HOME/.m2
