sudo: required
dist: trusty
addons:
  sonarcloud:
    organization: garethahealy-github
    token:
      secure: "eR0bx8DKoI5e9aLNicvDVoj7LXh6N8nFBzsCGQf3e3HP8cBj8NAp8dqqfOKasXOLVj2mKve0pOTXKjr1BizqFqW7w9GH4rUq9o0bxe5lIBRQjP2nUW9+hOwu+sTOD92cqHyzmT+r+6NwEfXVHurpe57RcRRkVB3CWBjkhWZ0lNc="
language: java
jdk:
- oraclejdk8
#before_install:
#- bash .travis/deploy-codesigning.sh
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
before_script:
- ./mvnw dependency:go-offline -B
script:
- ./mvnw clean install -B -Dgpg.skip=true -DskipTests
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B -DskipTests
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
