sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- bash .travis/deploy-codesigning.sh
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
script:
- mvn clean install -B -Dgpg.skip=true -DskipTests
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
